name: Main Branch PR Tests

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:

permissions: read-all

jobs:
  main-branch-tests:
    name: Run Tests on Main Branch PR
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Check Current Working Directory
        run: |
          pwd
        working-directory: .

      - name: Set Node 20
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20

      - name: Install Node.js Dependencies
        run: npm ci
        working-directory: .

      - name: Run Tests
        run: npm test
        working-directory: .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
